CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS agent_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    entity_id TEXT,
    timestamp TIMESTAMPTZ NOT NULL,
    payload JSONB NOT NULL,
    PRIMARY KEY (timestamp, id)
);

SELECT create_hypertable('agent_events', 'timestamp', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_agent_events_type_time ON agent_events (type, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_agent_events_entity_time ON agent_events (entity_id, timestamp DESC);

CREATE TABLE IF NOT EXISTS run_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    gamemode_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    elapsed_ms INTEGER NOT NULL CHECK (elapsed_ms > 0),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (completed_at, id)
);

SELECT create_hypertable('run_samples', 'completed_at', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_run_samples_gamemode_time ON run_samples (gamemode_id, completed_at DESC);
CREATE INDEX IF NOT EXISTS idx_run_samples_gamemode_elapsed ON run_samples (gamemode_id, elapsed_ms ASC);

CREATE TABLE IF NOT EXISTS economy_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    amount INTEGER,
    cosmetic_id TEXT,
    reason TEXT NOT NULL,
    balance INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (created_at, id)
);

SELECT create_hypertable('economy_ledger', 'created_at', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_economy_ledger_account_time ON economy_ledger (account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_economy_ledger_type_time ON economy_ledger (event_type, created_at DESC);

CREATE TABLE IF NOT EXISTS balances (
    account_id TEXT PRIMARY KEY,
    balance INTEGER NOT NULL DEFAULT 0 CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS owned_items (
    account_id TEXT NOT NULL,
    cosmetic_id TEXT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, cosmetic_id)
);

CREATE MATERIALIZED VIEW IF NOT EXISTS best_time_leaderboards_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', completed_at) AS bucket,
    gamemode_id,
    min(elapsed_ms) AS best_elapsed_ms,
    count(*) AS run_count
FROM run_samples
GROUP BY bucket, gamemode_id
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS lootbox_drop_rates_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', created_at) AS bucket,
    (payload->>'lootboxId') AS lootbox_id,
    cosmetic_id,
    count(*) AS drop_count
FROM economy_ledger
WHERE event_type = 'item_granted' AND payload ? 'lootboxId'
GROUP BY bucket, lootbox_id, cosmetic_id
WITH NO DATA;
